### PR TITLE
Add right arm model files

### PR DESCRIPTION
**Pull request by methylDragon**
This adds a set of SRDF and URDF files specific to a right-arm only set up.

I didn't do one for left-arm only setups because I can't test those with a physical arm.

### CODE REVIEW

**Comment by methylDragon** [comment]
Any updates for this? (:

**Comment by methylDragon** [comment]
The omission of this PR will break https://github.com/berkeleyopenarms/blue_moveit/pull/7

**Comment by wuphilipp** [comment]
Sorry for the delay. Looking into it now.

**Comment by wuphilipp** [comment]
Take a look at #7. I moved these updates over there so the changes are in one place.

**Pull request closed without merging**
