### PR TITLE
Create end effector pose reporter nodes

### PR DESCRIPTION
**Pull request by methylDragon**
Just some nodes to help get the pose of the end effector for each arm.

Will be quite useful for setting MoveIt! pose goals.

### CODE REVIEW

**Comment by brentyi** [comment]
Hm, are these nodes different from running `tf_echo` between the base and end effector links? Or are they just cleaner/easier to use/more explicit?

**Comment by methylDragon** [comment]
They're easier to read when trying to move the arm around and find its end effector position since it's all vertical. But I wrote this more for convenience for myself, so it's alright if this PR isn't merged in.

**Comment by brentyi** [comment]
That makes sense! I'm down to merge if these tools are documented (eg in the README?).

If we're making a `blue_helpers` package (as per berkeleyopenarms/blue_core#61), these could also go in there.

**Comment by wuphilipp** [comment]
We have added a blue_helpers metapackage. Feel free to add this here!
https://github.com/berkeleyopenarms/blue_helpers

**Comment by methylDragon** [comment]
Relevant PR added here: https://github.com/berkeleyopenarms/blue_helpers/pull/2

**Pull request closed without merging**
